### PR TITLE
Fix hatchet:setup_ci not printing

### LINKED ISSUE #219: Task `setup_ci` does not produce output
This code accidentally eats the output

```ruby
  task :setup_ci do
    script = File.expand_path(File.join(__dir__, "../../etc/ci_setup.rb"))
    out = `#{script}`
    raise "Command #{script.inspect} failed\n#{out}" unless $?.success?
  end
```

Should be

```ruby
  task :setup_ci do
    script = File.expand_path(File.join(__dir__, "../../etc/ci_setup.rb"))
    out = `#{script} 2>&1`
    puts out
    raise "Command #{script.inspect} failed\n#{out}" unless $?.success?
  end
```

### PR DESCRIPTION
**Pull request by schneems**
Close #219

GUS-W-19086600

### CODE REVIEW

File: lib/hatchet/tasks.rb [hunk 1]
```diff
@@ -1,7 +1,11 @@
 namespace :hatchet do
   task :setup_ci do
     script = File.expand_path(File.join(__dir__, "../../etc/ci_setup.rb"))
-    out = `#{script}`
+    puts "Running script `#{script}`"
+    out = `#{script} 2>&1`
+    puts "Done"
+    puts "Output:\n"
+    puts out
```
Comment (edmorley) [inline lib/hatchet/tasks.rb:8]: I think the output will be shown twice if the command fails. Should some of these new lines be moved after the `raise`, so they are only output if the failure message hasn't been printed?

**Review by edmorley — APPROVED** [review]

File: lib/hatchet/tasks.rb (hunk 1 above)
Comment (schneems) [reply lib/hatchet/tasks.rb:8]: I removed the duplicate output from the failure case, good catch.
